### PR TITLE
feat: working-directory with only-new-issues

### LINKED ISSUE #150: Error: options working-directory and only-new-issues aren't compatible
Hi,

I tried setting both `working-directory` and `only-new-issues` but got: `Error: options working-directory and only-new-issues aren't compatible`

I am working on a monorepo and would like to be able to get only new issues from the linter. How hard would be to allow it?

### PR DESCRIPTION
**Pull request by CfirTsabari**
Fixes #150

### CODE REVIEW

**Comment by CfirTsabari** [comment]
@ldez any chance you can review it?

**Comment by ldez** [comment]
> My company is really looking forward to this bugfix 🙏🏿

Sponsoring is a good way to sustain open-source maintainers: [sponsor me](https://github.com/sponsors/ldez)

**Comment by ldez** [comment]
Even, if my bank account is really looking forward to the money to allow me to eat, I reviewed the PR.

You can always [sponsor me](https://github.com/sponsors/ldez), sponsorship is always welcome, especially from commercial companies. :wink:

**Review by ldez — APPROVED** [review]
LGTM, thank you @CfirTsabari :+1:

**Comment by danielorbach** [comment]
Sorry for the delay @ldez
I have sponsored in the link you'd provided,
Hope you find the money to eat in your bank account soon 🥘 💰

**Comment by ldez** [comment]
Thanks, I appreciate it (and my bank account too :smile:)

**Pull request merged**
