### PR TITLE
Add path prefix if working directory specified

### PR DESCRIPTION
**Pull request by jwilner**
Following up on https://github.com/golangci/golangci-lint-action/issues/31 -- adds `--path-prefix` if `working-directory` is specified. 

Worth noting that this PR and this option basically have a dependency on https://github.com/golangci/golangci-lint/pull/1226

### CODE REVIEW

**Comment by SVilgelm** [comment]
you are so fast! :-)
I have just one concern - Will it work if the working-directory is an absolute path?

Is it possible to test GitHub Actions by specifying a commit id instead of version?

**Comment by jwilner** [comment]
@SVilgelm, even without path-prefix, I think specifying an absolute path for `working-directory` would be a surprising and brittle choice, since users would be coupling their build to the layout of the github action FS (which they don't control), rather than just the layout of their repository (which they do).

That said, nothing to stop people from doing it!

I think the path-prefix logic behaves reasonably in that scenario because it still prefers user override.

### relative path: ✅ 

working-directory: `subdir`
example output path: `subdir/path/to/file.go`

A relative path is the most likely usage pattern imo, and it works exactly like you'd want (and what GH wants).

### absolute path, no explicit `--path-prefix`: 🚫 

working-directory: `/foo/bar/myrepo/subdir`
output paths: `/foo/bar/myrepo/subdir/path/to/file.go`

I don't believe this will work with github-actions, because the error paths will no longer be relative to the repo. If, for an unknown reason, the user needs the absolute path, they can specify the path prefix explicitly, as shown below.

### absolute path, explicit `--path-prefix`: ✅ 

working-directory: `/foo/bar/myrepo/subdir`
args: '--path-prefix=subdir'
output paths: `subdir/path/to/file.go`

Because the logic prefers any explicit CLI path-prefix arg, the user still has the option to override the default behavior.

**Comment by SVilgelm** [comment]
@jwilner thank you for the explanation, I'm totally agree with you.

**Comment by SVilgelm** [comment]
@iwankgb it's great that you merged it, but It depends on the golangci/golangci-lint#1226 pull request, what is not merged yet and the action can fail with an error:
```
Can't get config for command line: can't parse args: unknown flag: --path-prefix
```

**Comment by sayboras** [comment]
I just merged https://github.com/golangci/golangci-lint/pull/1226, but I don't think there is a way to point to golangci-lint master branch, so we need to wait for release as well ?

**Comment by iwankgb** [comment]
Sorry, I have not realised it and have not read description carefully enough. Can any of you file a reverting PR, please?

**Comment by SVilgelm** [comment]
@jwilner no worries, that PR and a fix for that PR are already merged to master :)

**Comment by jwilner** [comment]
@svilgelm what's the procedure for cutting a new release of golangci-lint? Seems like it'd just be a patch version.

**Comment by SVilgelm** [comment]
@jwilner I never did it, probably we need to ask @sayboras. But according to the documentation[1] we just need to create a new tag.
But let's release the `golangci-lint` tool first, then the action

**Comment by iwankgb** [comment]
Beyond the tag some documentation must be generated

**Pull request merged**
