### PR TITLE
Try to get version from go.mod file

### LINKED ISSUE #106: Infer golangci-lint version from go.mod
For Go projects, I use `tools.go` to specify the tools the project depends on and pin the version in the `go.mod` file. This is pretty convenient. It would be awesome to have the action infer the version from the `go.mod` file. When upgrading, this makes it one file less to update the `golangci-lint` version.

With some guidance, I can probably tackle this. I'm just completely new to GitHub Actions.

### PR DESCRIPTION
**Pull request by lukasmalkmus**
This first implementation is a very naive approach: Assuming that the `go.mod` file is residing in the repository root (and thus the current working directory I guess).

If the `version` input is not set, the `go.mod` file is loaded, the version extracted from the `github.com/golangci/golangci-lint v1.32.0` line using a regex.

Closes #106.

### CODE REVIEW

**Review by SVilgelm — CHANGES_REQUESTED** [review]
Could you provide the links to prove, that this works?
comment dist changes (`npm run all`) then in a test pull request in your project instead of `uses: golangci/golangci-lint-action@v2` use `uses: lukasmalkmus/golangci-lint-action@go-mod-version`
and add the link for that commit here

**Comment by lukasmalkmus** [comment]
@SVilgelm Alright, added the `dist` changes. Here is a link to a project of mine: https://github.com/lukasmalkmus/expensify-go/runs/1931439340#step:4:12

**Comment by SVilgelm** [comment]
@lukasmalkmus Could you please rebase you PR?

**Comment by lukasmalkmus** [comment]
✅

**Review by SVilgelm — APPROVED** [review]
please execute `npm run all` and commit the changes

**Comment by SVilgelm** [comment]
@golangci/team  please review

**Review by SVilgelm — APPROVED** [review]

**Review by ldez — APPROVED** [review]

**Comment by SVilgelm** [comment]
released in v2.5.0

**Pull request merged**
