### PR TITLE
Remove Setup-Go

### PR DESCRIPTION
**Pull request by StevenACoffman**
Per discussion in #365, this removes `setup-go` dep. 

Until this PR is landed, we are stuck and unable to upgrade any dependencies, fix any vulns, due to the inability to build the `setup-go` package.

So now we remove it and then we will need to explicitly install go, like:
```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2  # <-- here
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
```

Of course, it will then require us to bump v3, but I imagine there are further documentation changes required so I am not doing that in this PR.

Signed-off-by: Steve Coffman <steve@khanacademy.org>

### CODE REVIEW

**Comment by SVilgelm** [comment]
Thank you very much for this PR, it looks good to me. Just one note: please update  all examples in readme, add the go installation step. I need few day for testing.

**Comment by kamilsk** [comment]
great

**Review by SVilgelm — CHANGES_REQUESTED** [review]
1. add go installation step in all examples in the README.md file
2. remove skip-go-installation option from action.yml and from README.md files

**Comment by SVilgelm** [comment]
Here is the PR I use for testing the changes for this action: https://github.com/sv-tools/mongoifc/pull/49
everything works fine so far

**Comment by StevenACoffman** [comment]
I think I have completed these references, but please let me know if additional ones are present, or if I should make further edits.

**Review by SVilgelm — APPROVED** [review]

**Review by SVilgelm — APPROVED** [review]

**Comment by magnetikonline** [comment]
Thanks for doing this work @StevenACoffman - great to see it finally in the new `@v3` action. 👍

**Pull request merged**
