### PR TITLE
Run the build after dependabot PR

### PR DESCRIPTION
**Pull request by sayboras**
A few dependabot PRs are merged recently. However, the build in those PR might not reflect what we have in repo due to files in _dist_ directory. So this PR is just for `npm run all` from master branch.

https://github.com/golangci/golangci-lint-action/pull/52
https://github.com/golangci/golangci-lint-action/pull/53

### CODE REVIEW

**Comment by SVilgelm** [comment]
the prettier was update, probably you just need to run `nom install`

**Comment by SVilgelm** [comment]
I did rebase for all prs before merging

**Comment by sayboras** [comment]
> I did rebase for all prs before merging

Yes, I am aware of that. This PR is just to re-generate files in dist/ directory. As during the build, I don't think we automatically commit if there is any changes.

**Comment by SVilgelm** [comment]
yeah, we need to block merging without rebuilding

**Comment by sayboras** [comment]
yeah, we need to investigate how to automate this as well. Mainly, it's coming from this line https://github.com/golangci/golangci-lint-action/blob/master/action.yml#L27

**Comment by SVilgelm** [comment]
we can do for any push to master branch run `npm run all` and if the files in dist folder were changed, then just make a direct commit to the master branch using. But we need a GitHub token with admin permissions for this repo

**Comment by SVilgelm** [comment]
or just block from merging, so someone need to do it manually and update a PR

**Pull request merged**
